config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :vehiculos
  resources :pasajeros
  resources :recorridos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'vehiculos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pasajero.rb
class Pasajero < ApplicationRecord
  has_many :vehiculos
  has_many :recorridos, through: :vehiculos
  accepts_nested_attributes_for :vehiculos, reject_if: :all_blank, allow_destroy: true

end

app/models/recorrido.rb
class Recorrido < ApplicationRecord
  has_many :vehiculos
  has_many :pasajeros,through: :vehiculos
  accepts_nested_attributes_for :vehiculos, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehiculo.rb
class Vehiculo < ApplicationRecord
  belongs_to :recorrido
  belongs_to :pasajero
  accepts_nested_attributes_for :pasajero, reject_if: :all_blank, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/pasajeros_controller.rb
class PasajerosController < ApplicationController
  before_action :set_pasajero, only: [:show, :edit, :update, :destroy]

  # GET /pasajeros
  # GET /pasajeros.json
  def index
    @pasajeros = Pasajero.all
  end

  # GET /pasajeros/1
  # GET /pasajeros/1.json
  def show
  end

  # GET /pasajeros/new
  def new
    @pasajero = Pasajero.new
  end

  # GET /pasajeros/1/edit
  def edit
  end

  # POST /pasajeros
  # POST /pasajeros.json
  def create
    @pasajero = Pasajero.new(pasajero_params)

    respond_to do |format|
      if @pasajero.save
        format.html { redirect_to @pasajero, notice: 'Pasajero was successfully created.' }
        format.json { render :show, status: :created, location: @pasajero }
      else
        format.html { render :new }
        format.json { render json: @pasajero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pasajeros/1
  # PATCH/PUT /pasajeros/1.json
  def update
    respond_to do |format|
      if @pasajero.update(pasajero_params)
        format.html { redirect_to @pasajero, notice: 'Pasajero was successfully updated.' }
        format.json { render :show, status: :ok, location: @pasajero }
      else
        format.html { render :edit }
        format.json { render json: @pasajero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pasajeros/1
  # DELETE /pasajeros/1.json
  def destroy
    @pasajero.destroy
    respond_to do |format|
      format.html { redirect_to pasajeros_url, notice: 'Pasajero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pasajero
      @pasajero = Pasajero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pasajero_params
      params.require(:pasajero).permit(:nombre)
    end
end

app/controllers/recorridos_controller.rb
class RecorridosController < ApplicationController
  before_action :set_recorrido, only: [:show, :edit, :update, :destroy]

  # GET /recorridos
  # GET /recorridos.json
  def index
    @recorridos = Recorrido.all
  end

  # GET /recorridos/1
  # GET /recorridos/1.json
  def show
  end

  # GET /recorridos/new
  def new
    @recorrido = Recorrido.new
  end

  # GET /recorridos/1/edit
  def edit
  end

  # POST /recorridos
  # POST /recorridos.json
  def create
    @recorrido = Recorrido.new(recorrido_params)

    respond_to do |format|
      if @recorrido.save
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully created.' }
        format.json { render :show, status: :created, location: @recorrido }
      else
        format.html { render :new }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recorridos/1
  # PATCH/PUT /recorridos/1.json
  def update
    respond_to do |format|
      if @recorrido.update(recorrido_params)
        format.html { redirect_to @recorrido, notice: 'Recorrido was successfully updated.' }
        format.json { render :show, status: :ok, location: @recorrido }
      else
        format.html { render :edit }
        format.json { render json: @recorrido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recorridos/1
  # DELETE /recorridos/1.json
  def destroy
    @recorrido.destroy
    respond_to do |format|
      format.html { redirect_to recorridos_url, notice: 'Recorrido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recorrido
      @recorrido = Recorrido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recorrido_params
      params.require(:recorrido).permit(:nombre, :vehiculos_attributes => [:id, :modelo, :recorrido_id, :pasajero_id, :_destroy,
                                                                            :pasajero_attributes=>[:id,:nombre]])
    end
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /vehiculos
  # GET /vehiculos.json
  def index
    @vehiculos = Vehiculo.all
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:modelo, :recorrido_id, :pasajero_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pasajeros_helper.rb
module PasajerosHelper
end

app/helpers/recorridos_helper.rb
module RecorridosHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaTransporteWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <%=render "layouts/partials/navigation"%>
  <body>
  <br>
  <br>
  <br>
  <center>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>


  </center>
  </body>
</html>

app/views/layouts/partials/_navigation.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
    </button>
    </div>
    <br><br>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav  nav-justified ">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>



        <li  class="table-bordered"><%= link_to "<span class='glyphicon glyphicon-road'></span> Inicio".html_safe,vehiculos_path %></li>
        <li  class="table-bordered"><%= link_to "<span class=' glyphicon glyphicon-road'></span>Recorridos".html_safe,recorridos_path  %></li>
        <li class="table-bordered"><%= link_to "<span class=' glyphicon glyphicon-user'></span>Pasajeros".html_safe,pasajeros_path  %></li>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/pasajeros/_form.html.erb
<%= form_with(model: pasajero, local: true) do |form| %>
  <% if pasajero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pasajero.errors.count, "error") %> prohibited this pasajero from being saved:</h2>

      <ul>
      <% pasajero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :pasajero_nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pasajeros/edit.html.erb
<h1>Editing Pasajero</h1>

<%= render 'form', pasajero: @pasajero %>

<%= link_to 'Show', @pasajero %> |
<%= link_to 'Back', pasajeros_path %>

app/views/pasajeros/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="jumbotron">
    <%= link_to "<span class='glyphicon glyphicon-user'></span> Nuevo pasajero".html_safe,
                new_pasajero_path, class: 'btn btn-success btn-lg active'%>
<h1>Pasajeros</h1>

    <div class="table-responsive">
      <table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pasajeros.each do |pasajero| %>
      <tr>
        <td><%= pasajero.nombre %></td>
        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe,
                      pasajero, class: 'btn btn-default btn-sm active'%>
        </div>

        </td>
        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe,
                      edit_pasajero_path(pasajero), class: 'btn btn-warning btn-sm active'%>
        </div>

        </td>

        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,
                      pasajero, method: :delete, data: { confirm: 'Eliminar?' }, class:"btn btn-success btn-sm active" %>
        </div>


      </tr>
  <%end%>

  </tbody>



  <br>
</table>
    </div>
  </div>
  </div>
</div>
</div>



</table>

app/views/pasajeros/new.html.erb
<h1>New Pasajero</h1>

<%= render 'form', pasajero: @pasajero %>

<%= link_to 'Back', pasajeros_path %>

app/views/pasajeros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pasajero.nombre %>
</p>

<%= link_to 'Edit', edit_pasajero_path(@pasajero) %> |
<%= link_to 'Back', pasajeros_path %>

app/views/recorridos/_form.html.erb
<%= form_with(model: recorrido, local: true) do |form| %>
  <% if recorrido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recorrido.errors.count, "error") %> prohibited this recorrido from being saved:</h2>

      <ul>
      <% recorrido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :recorrido_nombre %>
  </div>
    <div align="center">
      <%= link_to_add_association 'Añadir Vehiculo', form, :vehiculos,
                                  'data-association-insertion-node' => "#vehiculos-pasajero ol",
                                  'data-association-insertion-method' => "append",
                                  :wrap_object => Proc.new {|vehiculo| vehiculo.build_pasajero; vehiculo }%>
      <hr/>

      <fieldset id="vehiculos-pasajero">
        <ol>
          <%= form.fields_for :vehiculos do |vehiculo| %>
              <%= render partial: "vehiculo_fields", locals: { f:vehiculo } %>
          <%end%>
        </ol>
      </fieldset>

    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recorridos/_vehiculo_fields.html.erb
<li class="control-group nested-fields">
  <div class="controls">
  <%=f.label "Placa del carro" %>
  <%=f.text_field :modelo %>
  <%=f.label "Nombre del pasajero" %>
  <%= f.collection_select :pasajero_id, Pasajero.order(:nombre), :id, :nombre, include_blank: false%></td>
  <%=link_to_remove_association "Eliminar", f %></td>
  </div>
</li>

app/views/recorridos/edit.html.erb
<h1>Editing Recorrido</h1>

<%= render 'form', recorrido: @recorrido %>

<%= link_to 'Show', @recorrido %> |
<%= link_to 'Back', recorridos_path %>

app/views/recorridos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="jumbotron">
    <p align="right">
      <%= link_to "<span class='glyphicon glyphicon-road'></span> Nuevo Recorrido".html_safe,
                  new_recorrido_path, class: 'btn btn-success btn-lg active'%>
    </p>
    <h2 align="center" class="titulo"><strong>Recorridos</strong></h2>
    <hr>
    <div class="table-responsive">
      <table class="table">
        <thead>
        <tr>
          <th>Recorrido</th>

          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <% @recorridos.each do |recorrido| %>
            <tr>
              <td><%= recorrido.nombre %></td>

              <td> <div class="btn-group" role="group" aria-label="...">
                <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe,
                            recorrido, class: 'btn btn-default btn-sm active'%>
              </div>
              </td>
              <td> <div class="btn-group" role="group" aria-label="...">
                <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe,
                            edit_recorrido_path(recorrido), class: 'btn btn-warning btn-sm active'%>
              </div>

              </td>

              <td> <div class="btn-group" role="group" aria-label="...">
                <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,
                            recorrido, method: :delete, data: { confirm: 'Eliminar?' }, class:"btn btn-success btn-sm active" %>
              </div>

              </td>

            </tr>
        <%end%>

        </tbody>



        <br>
      </table>
    </div>
  </div>
</div>



</table>

</body>

app/views/recorridos/new.html.erb
<h1>New Recorrido</h1>

<%= render 'form', recorrido: @recorrido %>

<%= link_to 'Back', recorridos_path %>

app/views/recorridos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @recorrido.nombre %>
</p>

<%= link_to 'Edit', edit_recorrido_path(@recorrido) %> |
<%= link_to 'Back', recorridos_path %>

app/views/vehiculos/_form.html.erb
<%= form_with(model: vehiculo, local: true) do |form| %>
  <% if vehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehiculo.errors.count, "error") %> prohibited this vehiculo from being saved:</h2>

      <ul>
      <% vehiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Placa del carro" %>
    <%= form.text_field :modelo, id: :vehiculo_modelo %>
  </div>

  <div class="field">
    <%= form.label :recorrido_id %>
    <%= form.collection_select :recorrido_id, Recorrido.order(:nombre), :id, :nombre, include_blank: true%></td>
  </div>

  <div class="field">
    <%= form.label :pasajero_id %>
    <%= form.collection_select :pasajero_id, Pasajero.order(:nombre), :id, :nombre, include_blank: true%></td>
  </div>

  <div class="actions">
    <%= form.submit "Guardar recorrido" %>
  </div>
<% end %>

app/views/vehiculos/edit.html.erb
<body>
<h1>Editar Vehiculo</h1>

<%= render 'form', vehiculo: @vehiculo %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>
</body>

app/views/vehiculos/index.html.erb
<body>
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="jumbotron">
<h1>Vehiculos</h1>
    <div class="table-responsive">
      <table class="table">
  <thead>
    <tr>
      <th>Placa del Carro</th>
      <th>Recorrido</th>
      <th>Pasajero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehiculos.each do |vehiculo| %>
      <tr>
        <td><%= vehiculo.modelo %></td>
        <td><%= vehiculo.recorrido.nombre %></td>
        <td><%= vehiculo.pasajero.nombre %></td>
        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-eye-open'></span>".html_safe,
                      vehiculo, class: 'btn btn-default btn-sm active'%>
        </div>

        </td>
        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe,
                     edit_vehiculo_path(vehiculo), class: 'btn btn-warning btn-sm active'%>
        </div>

        </td>

        <td> <div class="btn-group" role="group" aria-label="...">
          <%= link_to "<span class='glyphicon glyphicon-trash'></span>".html_safe,
                      vehiculo, method: :delete, data: { confirm: 'Eliminar?' }, class:"btn btn-success btn-sm active" %>
        </div>

        </td>

      </tr>
  <%end%>

  </tbody>



  <br>
</table>
</div>
</div>
</div>
</body>

app/views/vehiculos/new.html.erb
<body>
<div class="container" >
  <div class="jumbotron">
    <h2 align="center">Vehiculo</h2>
    <p align="right"><%= link_to " Atras".html_safe,
                                 vehiculos_path , class: 'btn btn-success btn-lg active'%>
      <%= render 'form', vehiculo: @vehiculo %>
    </p></div></div>

</body>

app/views/vehiculos/show.html.erb
<body>
<br>
<br>
<br>
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @vehiculo.modelo %>
</p>

<p>
  <strong>Recorrido:</strong>
  <%= @vehiculo.recorrido.nombre %>
</p>

<p>
  <strong>Pasajero:</strong>
  <%= @vehiculo.pasajero.nombre %>
</p>

<div  class="btn-group" role="group" aria-label="...">
  <%= link_to "Editar Vehiculo".html_safe,
              edit_vehiculo_path(@vehiculo) , class: 'btn btn-success btn-lg active'%>
</div>
<div  class="btn-group" role="group" aria-label="...">
  <%= link_to " Atras".html_safe,
              vehiculos_path , class: 'btn btn-success btn-lg active'%>
</div>
</body>